Fixed the mathematical equations under section 3.1 and 3.3
CIS-522/course-content pull request #3
Opened 2023-01-25 05:35 UTC by haoershi

2023-01-28 05:49 UTC, fyy26 requested changes
There seems to be lots of output and metadata changes that aren't relevant to the fix - could you get the code delta down to just the lines containing the fix?

2023-01-30 09:30 UTC, haoershi commented
Sorry about the late response, I think the changes should be limited to the fixed lines now.

2023-02-01 21:07 UTC, andrewlr09 approved these changes

2023-02-02 10:53 UTC, j6k4m8 commented
Awesome, thank you!!

2023-02-02 10:53 UTC, merged